all:
  children:
    routers:
      hosts:
        R1:
          loopback_ip: 1.1.1.1
        R2:
          loopback_ip: 2.2.2.2
        R3:
          loopback_ip: 3.3.3.3
        R4:
          loopback_ip: 4.4.4.4
        R5:
          loopback_ip: 5.5.5.5
        R6:
          loopback_ip: 6.6.6.6
    
    as61001:
      hosts:
        R1:
        R2:
    as61002:
      hosts:
        R3:
        R4:
    as61003:
      hosts:
        R5:
        R6:

  hosts:
    R1:
      ansible_host: 192.168.122.101
      ansible_user: sam
      ansible_ssh_pass: "sam"
      ansible_network_os: ios
      ansible_connection: network_cli
    R2:
      ansible_host: 192.168.122.102
      ansible_user: sam
      ansible_ssh_pass: "sam"
      ansible_network_os: ios
      ansible_connection: network_cli
    R3:
      ansible_host: 192.168.122.103
      ansible_user: sam
      ansible_ssh_pass: "sam"
      ansible_network_os: ios
      ansible_connection: network_cli
    R4:
      ansible_host: 192.168.122.104
      ansible_user: sam
      ansible_ssh_pass: "sam"
      ansible_network_os: ios
      ansible_connection: network_cli
    R5:
      ansible_host: 192.168.122.105
      ansible_user: sam
      ansible_ssh_pass: "sam"
      ansible_network_os: ios
      ansible_connection: network_cli
    R6:
      ansible_host: 192.168.122.106
      ansible_user: sam
      ansible_ssh_pass: "sam"
      ansible_network_os: ios
      ansible_connection: network_cli

