---
- name: configure OSPF for each AS
  hosts: routers
  gather_facts: false
  vars:
    ospf_config:
      as61001:
        process_id: 1
        area: 0
        networks:
          - 1.1.1.1 0.0.0.0 
          - 2.2.2.2 0.0.0.0
          - 10.0.12.0 0.0.0.3
      as61002:
        process_id: 1
        area: 0
        networks:
          - 3.3.3.3 0.0.0.0
          - 4.4.4.4 0.0.0.0
          - 10.0.14.0 0.0.0.3
      as61003:
        process_id: 1
        area: 0
        networks:
          - 5.5.5.5 0.0.0.0
          - 6.6.6.6 0.0.0.0
          - 10.0.16.0 0.0.0.3


  tasks:
    - name: get AS group membership
      set_fact:
        as_group: "{{group_names | select('match', 'as61.*') | first}}"

    - name: configure ospf process
      cisco.ios.ios_config:
        lines:
          - router ospf {{ospf_config[as_group].process_id}}
          - router-id {{hostvars[inventory_hostname].loopback_ip}}
          - passive-interface Loopback0
        parents: router ospf {{ospf_config[as_group].process_id}}
      when: as_group is defined

    - name: advertise OSPF networks
      cisco.ios.ios_config:
        lines:
          - network {{item}} area {{ospf_config[as_group].area}}
        parents: router ospf {{ospf_config[as_group].process_id}}
      loop: "{{ospf_config[as_group].networks}}"
      when: as_group is defined

    - name: enable OSPF on internal interfaces
      cisco.ios.ios_config:
        lines:
          - ip ospf {{ospf_config[as_group].process_id}} area {{ospf_config[as_group].area}} 
        parents: interface f1/0
      when: as_group is defined