- name: configure SNMPv2c on routers
  hosts: all
  gather_facts: false
  tasks:
    - name: configure SNMP community
      cisco.ios.ios_config:
        commands:
          - "snmp-server community public RO"

    - name: save config
      cisco.ios.ios_config:
        save_when: always
