FROM python:3.11-slim

ENV WORKSPACE=/ansible-workspace

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    git \
    ssh \
    vim \
    net-tools \
    iputils-ping \
    tcpdump \
    telnet \
    libssl-dev \
    build-essential \
    cron && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir --upgrade \
    ansible \
    netmiko \
    ntc-ansible \
    napalm \
    paramiko \
    pyats \
    requests

RUN ansible-galaxy collection install \
    cisco.ios \
    junipernetworks.junos \
    arista.eos \
    community.general

RUN mkdir -p ${WORKSPACE}
RUN git clone https://github.com/TPandaz/Network-Automation.git ${WORKSPACE}
WORKDIR ${WORKSPACE}

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
